### ISSUE TITLE
Why is the factor 2.239 needed in the mph_to_kph conversion?

### ISSUE THREAD

**Issue by JohnPlayerSpecial** [playhelp999/F1metry#4]
I would have coded  only this

mph_to_kmh = 1.60934

Thanks

**Comment by ilbuonmarcio** [comment]
Yeah, it seems reasonable!

EDIT: Now i see, values retrieved from the C's struct aren't from 0 to N, but they are represented in a strange way, and with this first factor we sort of mapped that value to represent real speeds.

Check them ingame and see!
